In [1]:
import yaml
import pickle

In [2]:
config_file = "../config_multiscope/dot_multi_vpn_scale5k10k.yaml"
with open(config_file, 'r') as file:
    config = yaml.safe_load(file)

In [3]:
p_filename = "../" + config['experiment_name'] + "_ts.pkl"

with open(p_filename, 'rb') as file:
    src = pickle.load(file)
    dst = pickle.load(file)

In [4]:
dst['/tordata/config/group_0_user_0']

                         text_len  count
time
2025-05-07 11:08:42.654        86      1
2025-05-07 11:08:45.987      1381      5
2025-05-07 11:08:49.320       892      3
2025-05-07 11:08:52.653       834      2
2025-05-07 11:08:55.986         0      0
...                           ...    ...
2025-05-07 12:53:12.027         0      0
2025-05-07 12:53:15.360         0      0
2025-05-07 12:53:18.693         0      0
2025-05-07 12:53:22.026         0      0
2025-05-07 12:53:25.359       275      1

[1886 rows x 2 columns]

In [5]:
src['102.0.0.10']

,ip.len,tcp.dstport,tcp.ack,tcp.len,tcp.reassembled.length,tcp.time_relative,tcp.time_delta,count,ip.len_ISP1-all,tcp.dstport_ISP1-all,...,tcp.time_delta_Service-2,count_Service-2,ip.len_Service-3,tcp.dstport_Service-3,tcp.ack_Service-3,tcp.len_Service-3,tcp.time_relative_Service-3,tcp.time_delta_Service-3,count_Service-3,frame.time
frame.time,,,,,,,,,,,,,,,,,,,,,
2025-05-07 11:02:22.692,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:22.692
2025-05-07 11:02:26.025,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:26.025
2025-05-07 11:02:29.358,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:29.358
2025-05-07 11:02:32.691,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:32.691
2025-05-07 11:02:36.024,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:36.024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-07 13:07:15.276,48174.0,5537214.0,6.076309e+09,34726.0,414.0,30940.861775,7701.097852,256.0,16133.0,1889975.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:15.276
2025-05-07 13:07:18.609,6258.0,243136.0,1.800000e+01,5170.0,0.0,25.710770,8.345646,20.0,3129.0,121568.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:18.609
2025-05-07 13:07:21.942,46764.0,5668570.0,1.750070e+05,33620.0,0.0,185.461075,19.663837,250.0,15486.0,1772017.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:21.942
2025-05-07 13:07:25.275,50546.0,5194092.0,1.527244e+11,36762.0,414.0,281621.183445,34661.125352,264.0,17287.0,1581275.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:25.275
2025-05-07 13:07:28.608,32484.0,2844860.0,4.086340e+10,24636.0,0.0,166664.076331,24690.923332,150.0,12321.0,1021414.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:28.608

In [6]:
import pandas as pd 

def ts2nccvec(ts: pd.core.frame.DataFrame):
    sample_offset = ((len(ts)-1)**0.5)
    return (ts - ts.mean()) / (ts.std()*sample_offset)
    
vec = ts2nccvec(dst['/tordata/config/group_0_user_0']["text_len"])
vec

time
2025-05-07 11:08:42.654    0.010454
2025-05-07 11:08:45.987    0.221625
2025-05-07 11:08:49.320    0.141886
2025-05-07 11:08:52.653    0.132428
2025-05-07 11:08:55.986   -0.003570
                             ...
2025-05-07 12:53:12.027   -0.003570
2025-05-07 12:53:15.360   -0.003570
2025-05-07 12:53:18.693   -0.003570
2025-05-07 12:53:22.026   -0.003570
2025-05-07 12:53:25.359    0.041274
Name: text_len, Length: 1886, dtype: float64

In [7]:
import numpy as np
np.dot(vec.to_numpy(), vec.to_numpy())

np.float64(0.999999999999999)

### Todo
- **Find way to align dataset**
    - chunk, fill zeros, etc
    - _Last big thing to do before all out test of method_
- Get end to end working
    - Send pcaps dfs through ncc GIS stuff
- Run new experiment loop
    - run through all features/combos and report metrics

In [8]:
scale_factor = 300
chunk_size = td = pd.Timedelta(1, "W")/scale_factor
chunk_size

Timedelta('0 days 00:33:36')

In [9]:
start = min([src[ip].index[0] for ip in src])
start

Timestamp('2025-05-07 11:02:22.692000')

In [10]:
# Fill zeros in missing indexes
full_index = pd.Index([])

for ip in src:
    full_index = full_index.union(src[ip].index)
    
for user in dst:
    full_index = full_index.union(dst[user].index)
print(full_index)
for ip in src:
    src[ip] = src[ip].reindex(full_index, fill_value=0)

for user in dst:
    dst[user] = dst[user].reindex(full_index, fill_value=0)

Index([2025-05-07 11:02:22.692000, 2025-05-07 11:02:26.025000,
       2025-05-07 11:02:29.358000, 2025-05-07 11:02:32.691000,
       2025-05-07 11:02:36.024000, 2025-05-07 11:02:39.357000,
       2025-05-07 11:02:42.690000, 2025-05-07 11:02:46.023000,
       2025-05-07 11:02:49.356000, 2025-05-07 11:02:52.689000,
       ...
       2025-05-07 14:41:04.713000, 2025-05-07 14:41:08.046000,
       2025-05-07 14:41:11.379000, 2025-05-07 14:41:14.712000,
       2025-05-07 14:41:18.045000, 2025-05-07 14:41:21.378000,
       2025-05-07 14:41:24.711000, 2025-05-07 14:41:28.044000,
       2025-05-07 14:41:31.377000, 2025-05-07 14:41:34.710000],
      dtype='object', length=3947)

In [11]:
src_chunks = {}

for ip in src:
    cur = start
    end = src[ip].index[-1]
    src_chunks[ip] = {}
    
    while cur < end:
        src_chunks[ip][cur] = src[ip][cur:cur+chunk_size]
        cur += chunk_size

dst_chunks = {}

for user in dst:
    cur = start
    end = dst[user].index[-1]
    dst_chunks[user] = {}
    
    while cur < end:
        dst_chunks[user][cur] = dst[user][cur:cur+chunk_size]
        cur += chunk_size

In [12]:
# - fill out zeros in the other timestamps for smaller chunks (could do this before or after chunking)
# - copy NCCTree class over
# - Send through as test (def eval(src_chunks[f], dst_chunks[f], label_func) -> List[Metrics] )
# - Setup experiment full loop (loop over all feature combos and multithread, save out to a file)

In [13]:
dst_chunks['/tordata/config/group_0_user_0'][pd.Timestamp('2025-05-07 11:02:22.692000')]

                            text_len  count
2025-05-07 11:02:22.692000         0      0
2025-05-07 11:02:26.025000         0      0
2025-05-07 11:02:29.358000         0      0
2025-05-07 11:02:32.691000         0      0
2025-05-07 11:02:36.024000         0      0
...                              ...    ...
2025-05-07 11:35:42.492000         0      0
2025-05-07 11:35:45.825000         0      0
2025-05-07 11:35:49.158000         0      0
2025-05-07 11:35:52.491000         0      0
2025-05-07 11:35:55.824000         0      0

[605 rows x 2 columns]

In [31]:
def eval_model(src, src_feature, dst, dst_feature, label_func, metric_func) -> {str: float}:
    output = model(src, src_feature, dst, dst_feature)
    labels = label_func(src_chunks)
    return metric_func(output, labels)

In [15]:
import math
def ip_to_user_multi(ip, group_size=5, starting=10):
    num_isps = 10
    isp = int(int(ip.split(".")[-2]))
    node_number = (int(ip.split(".")[-1]) - starting )*num_isps + isp
    user = node_number % group_size
    group = math.floor(node_number / group_size)
    return '/tordata/config/group_' + str(group) + "_user_" + str(user)
    
def label_f(d) -> {str: str}:
    result = {}
    for k in d:
        result[k] = ip_to_user_multi(k)
    return result

print(src.keys())
print(ip_to_user_multi('102.0.8.13'))

dict_keys(['102.0.0.19', '102.0.0.10', '102.0.0.16', '102.0.0.11', '102.0.0.15', '102.0.0.18', '102.0.0.14', '102.0.0.12', '102.0.0.13', '102.0.0.17'])
/tordata/config/group_7_user_3

In [26]:
def metric_f(output, labels):
    correct = 0.0
    for x in output:
        if output[x][0][0] == labels[x]:
            correct += 1
    accuracy = correct/len(output)
    return accuracy

In [106]:
import sys
import os
from tqdm import tqdm
sys.path.append("./NCC")
from NCC import NCCTree

def get_ts(p, feature):
    time = pd.Timestamp('2025-05-07 11:02:22.692000')
    #return p[time][feature].to_numpy()
    return p[feature].to_numpy()

def model(src_chunks, src_feature, dst_chunks, dst_feature, disable_bar=True) -> {str: [(str, float)]}:
    result = {}

    #noise_floor = np.mean([smallest_gt_zero(ts2nccvec(dst[user]['count'])) for user in dst])
    
    tree = NCCTree(3947)
    for p in tqdm(dst_chunks, disable=disable_bar):
        ts = get_ts(dst_chunks[p], dst_feature)
        # advoid divide by zero if all zeros 
        if (ts == 0).all(): continue
        vec = ts2nccvec(ts)
        assert abs(1 - np.linalg.norm(vec)) < 0.001
        tree.insert(vec, p)

    for _ in range(10):
        for p in tqdm(src_chunks, disable=disable_bar):
            vec = ts2nccvec(get_ts(src_chunks[p], src_feature))
            #vec[vec < noise_floor] = 0
            n = tree.ncc(vec, 2)
            #print(ip_to_user_multi(p), n)
            result[p] = n
        
        # if in and out are set to the same then this confirms it works correctly
        # assert(all(n[i] >= n[i + 1] for i in range(len(n) - 1)))
    
    return result
model(src, 'count_ISP1-1', dst, 'count')

{'102.0.0.19': [('/tordata/config/group_18_user_0',
   np.float64(0.21456117629193505)),
  ('/tordata/config/group_8_user_1', np.float64(0.08660002467068123))],
 '102.0.0.10': [('/tordata/config/group_0_user_0',
   np.float64(0.4047727281015301)),
  ('/tordata/config/group_1_user_2', np.float64(0.17954784608715016))],
 '102.0.0.16': [('/tordata/config/group_12_user_0',
   np.float64(0.38180967100803886)),
  ('/tordata/config/group_12_user_1', np.float64(0.16739429027195715))],
 '102.0.0.11': [('/tordata/config/group_2_user_0',
   np.float64(0.3800811107346311)),
  ('/tordata/config/group_5_user_1', np.float64(0.14081067084939342))],
 '102.0.0.15': [('/tordata/config/group_10_user_0',
   np.float64(0.3168269720558776)),
  ('/tordata/config/group_13_user_3', np.float64(0.12712847302585104))],
 '102.0.0.18': [('/tordata/config/group_16_user_0',
   np.float64(0.2864407717717402)),
  ('/tordata/config/group_8_user_1', np.float64(0.09193797022196941))],
 '102.0.0.14': [('/tordata/config/group_8_user_0',
   np.float64(0.35069929041132086)),
  ('/tordata/config/group_10_user_1', np.float64(0.1490301550577357))],
 '102.0.0.12': [('/tordata/config/group_4_user_0',
   np.float64(0.414527237944185)),
  ('/tordata/config/group_4_user_2', np.float64(0.21409615262103932))],
 '102.0.0.13': [('/tordata/config/group_6_user_0',
   np.float64(0.4037766724008513)),
  ('/tordata/config/group_5_user_2', np.float64(0.24193735537198802))],
 '102.0.0.17': [('/tordata/config/group_14_user_0',
   np.float64(0.2755283371921376)),
  ('/tordata/config/group_9_user_0', np.float64(0.11223646262983292))]}

In [109]:
%%time
eval_model(src, 'count', dst, 'count', label_f, metric_f)

CPU times: user 683 ms, sys: 7.84 ms, total: 691 ms
Wall time: 697 ms

1.0

In [60]:
def eval_all(src, dst, label_f, metric_f):
    # WARN: This assumes all entries have the same features
    src_features = list(src.values())[0].columns
    dst_features = list(dst.values())[0].columns
    bad_features = ['frame.time']

    results = pd.DataFrame(columns=['src_feature', 'dst_feature', 'accuracy'])
    for df in dst_features:
        for sf in tqdm(src_features):
            if sf in bad_features: continue
            results.loc[len(results)] = {
                'src_feature': sf, 
                'dst_feature': df,
                'accuracy': eval_model(src, sf, dst, df, label_f, metric_f)
            }
    return results

eval_all(src, dst, label_f, metric_f)

 32%|███████████████████████████████████████▌                                                                                     | 38/120 [00:06<00:12,  6.33it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 37%|█████████████████████████████████████████████▊                                                                               | 44/120 [00:07<00:13,  5.82it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 44%|███████████████████████████████████████████████████████▏                                                                     | 53/120 [00:09<00:13,  4.92it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 45%|████████████████████████████████████████████████████████▎                                                                    | 54/120 [00:09<00:12,  5.19it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 52%|█████████████████████████████████████████████████████████████████▋                                                           | 63/120 [00:11<00:12,  4.72it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 53%|██████████████████████████████████████████████████████████████████▋                                                          | 64/120 [00:11<00:10,  5.14it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 62%|█████████████████████████████████████████████████████████████████████████████                                                | 74/120 [00:13<00:07,  5.97it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 66%|██████████████████████████████████████████████████████████████████████████████████▎                                          | 79/120 [00:14<00:07,  5.16it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 67%|███████████████████████████████████████████████████████████████████████████████████▎                                         | 80/120 [00:14<00:07,  5.50it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 68%|████████████████████████████████████████████████████████████████████████████████████▍                                        | 81/120 [00:14<00:06,  5.74it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 69%|██████████████████████████████████████████████████████████████████████████████████████▍                                      | 83/120 [00:15<00:06,  5.90it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 70%|███████████████████████████████████████████████████████████████████████████████████████▌                                     | 84/120 [00:15<00:06,  5.98it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 72%|█████████████████████████████████████████████████████████████████████████████████████████▌                                   | 86/120 [00:15<00:05,  6.19it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 72%|██████████████████████████████████████████████████████████████████████████████████████████▋                                  | 87/120 [00:15<00:05,  6.26it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 73%|███████████████████████████████████████████████████████████████████████████████████████████▋                                 | 88/120 [00:15<00:05,  6.26it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 94/120 [00:16<00:04,  6.22it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120/120 [00:21<00:00,  5.59it/s]
 32%|███████████████████████████████████████▌                                                                                     | 38/120 [00:06<00:12,  6.32it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 37%|█████████████████████████████████████████████▊                                                                               | 44/120 [00:07<00:13,  5.65it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 44%|███████████████████████████████████████████████████████▏                                                                     | 53/120 [00:09<00:11,  5.89it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 45%|████████████████████████████████████████████████████████▎                                                                    | 54/120 [00:09<00:11,  5.89it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 52%|█████████████████████████████████████████████████████████████████▋                                                           | 63/120 [00:11<00:11,  4.76it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 53%|██████████████████████████████████████████████████████████████████▋                                                          | 64/120 [00:11<00:10,  5.15it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 62%|█████████████████████████████████████████████████████████████████████████████                                                | 74/120 [00:13<00:08,  5.16it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 66%|██████████████████████████████████████████████████████████████████████████████████▎                                          | 79/120 [00:14<00:07,  5.33it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 67%|███████████████████████████████████████████████████████████████████████████████████▎                                         | 80/120 [00:14<00:07,  5.58it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 68%|████████████████████████████████████████████████████████████████████████████████████▍                                        | 81/120 [00:14<00:06,  5.68it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 69%|██████████████████████████████████████████████████████████████████████████████████████▍                                      | 83/120 [00:15<00:06,  5.36it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 70%|███████████████████████████████████████████████████████████████████████████████████████▌                                     | 84/120 [00:15<00:07,  4.59it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 72%|█████████████████████████████████████████████████████████████████████████████████████████▌                                   | 86/120 [00:15<00:06,  5.00it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 72%|██████████████████████████████████████████████████████████████████████████████████████████▋                                  | 87/120 [00:15<00:06,  5.41it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 73%|███████████████████████████████████████████████████████████████████████████████████████████▋                                 | 88/120 [00:16<00:05,  5.48it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
 78%|█████████████████████████████████████████████████████████████████████████████████████████████████▉                           | 94/120 [00:17<00:06,  4.27it/s]/tmp/ipykernel_37135/1028957165.py:5: RuntimeWarning: invalid value encountered in divide
  return (ts - ts.mean()) / (ts.std()*sample_offset)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120/120 [00:23<00:00,  5.07it/s]

                     src_feature dst_feature  accuracy
0                         ip.len    text_len       1.0
1                    tcp.dstport    text_len       1.0
2                        tcp.ack    text_len       0.2
3                        tcp.len    text_len       1.0
4         tcp.reassembled.length    text_len       1.0
..                           ...         ...       ...
233            tcp.ack_Service-3       count       0.6
234            tcp.len_Service-3       count       1.0
235  tcp.time_relative_Service-3       count       0.8
236     tcp.time_delta_Service-3       count       0.8
237              count_Service-3       count       1.0

[238 rows x 3 columns]

Index(['ip.len', 'tcp.dstport', 'tcp.ack', 'tcp.len', 'tcp.reassembled.length',
       'tcp.time_relative', 'tcp.time_delta', 'count', 'ip.len_ISP1-all',
       'tcp.dstport_ISP1-all',
       ...
       'tcp.time_delta_Service-2', 'count_Service-2', 'ip.len_Service-3',
       'tcp.dstport_Service-3', 'tcp.ack_Service-3', 'tcp.len_Service-3',
       'tcp.time_relative_Service-3', 'tcp.time_delta_Service-3',
       'count_Service-3', 'frame.time'],
      dtype='object', length=120)

In [ ]:
def smallest_gt_zero(df):
    return min(df[df > 0])
smallest_gt_zero(y2)

In [ ]:
import matplotlib.pyplot as plt
import datetime

noise_floor = np.mean([smallest_gt_zero(ts2nccvec(dst[user]['count'])) for user in dst])

x = src['102.0.0.10'].index
y = ts2nccvec(src['102.0.0.10']['count'])
y2 = ts2nccvec(dst['/tordata/config/group_0_user_0']['count'])

y.loc[y < noise_floor] = 0


plt.plot(x,y)
plt.plot(x, y2)
plt.show()
np.dot(y.to_numpy(), y2.to_numpy())#/np.dot(y.to_numpy(), y.to_numpy())

In [ ]:
pd.unique(y2)
y2

In [ ]:
np.min([smallest_gt_zero(ts2nccvec(dst[user]['count'])) for user in dst])

In [ ]:
list(src['102.0.0.10'].columns)

In [117]:
def model_OLD(src_raw, src_feature, dst_raw, dst_feature):
    import statsmodels.api as sm
    def ccf_calc(sig1, sig2):
        corr = sm.tsa.stattools.ccf(sig2, sig1, adjusted=False, nlags=1)
    
        # Remove padding and reverse the order
        return corr[0:(len(sig2)+1)][::-1]


    def cross_cor(ts1, ts2, debug=False, max_offset=300, only_positive=True):
        ccf = ccf_calc(ts1, ts2)
        best_cor = max(ccf)
        best_lag = np.argmax(ccf)
    
        if debug:
            print('best cross correlation: ' + str(best_cor) + " at time lag: " + str(best_lag))
            print(len(ccf))
            print(ccf)
            ccf_plot(range(len(ccf)), ccf)
        return best_cor, best_lag

    def compare_ts(ts1, ts2, debug=False):
        # dtw_classic, path_classic = dtw(ts1, ts2, dist='square',
        #                             method='classic', return_path=True)
        # return dtw_classic
        # print(ts1)
        # print(ts2)
        # dist, lag = cross_cor(pd.Series(ts1), pd.Series(ts2))
        dist, lag = cross_cor(ts1, ts2, debug=debug)
        # assert dist >= -1 and dist <= 1
        dist = dist * -1  # flip for use as distance metric
        # assert dist >= -1 and dist <= 1
        return dist, lag

    def compare_ts_reshape(ts1, ts2, debug=False):
        ts1 = ts1.fillna(0)
        ts2 = ts2.fillna(0)
    
        range = min(ts2.index.values), max(ts2.index.values)
        ts1 = ts1.loc[(ts1.index >= range[0]) & (ts1.index <= range[1])]
    
        # ts1 = ts1.loc[:, 'tda_pl']
        ts1 = ts1.values
    
        ts1_norm = np.array(ts1)
        ts2_norm = np.array(ts2)
    
        # delay = 0
    
        # ts1_norm.index = ts1_norm.index + pd.DateOffset(seconds=delay)
    
        # lock to same range with buffer room
        # on each side to account for network (or PPT) delay
    
        # detect if no overlap
        if len(ts1_norm) < 2 or len(ts2_norm) < 2:
            return float("inf"), 0
    
        # Normalize peaks?
        # ts1_norm = normalize_ts(ts1_norm)
        # ts2_norm = normalize_ts(ts2_norm)
    
        # plot_ts(ts1_norm, ts2_norm)
        # exit(1)
    
        # else:
        #     ts1_norm = ts1_norm.tolist()
        #     ts2_norm = ts2_norm.tolist()
    
        score, lag = compare_ts(ts1_norm, ts2_norm, debug=debug)
        # adj_score = score + (((lag+1)**1.1)/1000.0)
        return score, lag

    src = {}
    dst = {}
    for ip in src_raw:
        src[ip] = src_raw[ip][src_feature]
    for user in dst_raw:
        dst[user] = dst_raw[user][dst_feature]
        
    correct = 0.0
    for user in dst:
        best_score = 0
        best_user = 0
        for _ in range(10):
            for ip in src:
                score = sm.tsa.stattools.ccf(src[ip].values, dst[user].values, adjusted=False, nlags=1)
                if score > best_score:
                    best_score = score
                    best_user = ip_to_user_multi(ip)
        if user == best_user:
            correct += 1
    accuracy = correct / len(src)
    return accuracy

In [118]:
%%time
model_OLD(src, 'count', dst, 'count')

CPU times: user 1.66 s, sys: 19 μs, total: 1.66 s
Wall time: 1.66 s

1.0